### ISSUE TITLE
Usage docs?

### ISSUE THREAD

**Issue by oyeanuj** [JDvorak/recode#1]
Hi @JDvorak! @wooorm referred me to your library. I am curious to understand how 'retext for code' works? It would be great to have an example of the possible usage.

Thank you for putting out your work :)

**Comment by JDvorak** [comment]
Ah, yeah, I'm still cleaning up some edge cases and refactoring, but you can use it now as just as you would use retext, so if you were to pretend you are using @wooorm's retext library, but instead of putting in human language, you put in a VFile containing the string contents of a javascript file, then you will be able to attach plugins to it-- just as you would use with retext. On the other end, this will return a generated string of javascript from the tree provided to the plugins.

However, I'll do better than this, and get you full documentation this week.

**Comment by wooorm** [comment]
👍 

@JDvorak Awesome! Two more Qs:

1. Do you have ideas for plugins?
2. Can I help?

**Comment by JDvorak** [comment]
**1.** Yes, this tool was originally devised for the purpose of building out a set of plugins that converted trees of jasmine/mocha/tape test suites into enriched annotated trees that can then be converted into markdown. But, here are all the plugins which would be cool:
- The one (or set) I just mentioned, an annotation library (or libraries) to mark up the tree with 'assertion,' 'suite,' 'case,' node labels for purposes of later generation of prettily printed test documentation. There are slight variations between Mocha-Chai, Jasmine, QUnit, and massive variations between the outliers like Tape, or Vows. 
- ESLint/ESHint compatible plugin which writes to VFile messages.
- Plugin which enriches the comment text nodes by interpreting their jsdoc annotations.
- Plugin which detects when variables and function names are too proximate to one another in spelling (such as when the Levenshtein distance is close enough that a typo would be generative of silent bugs)
- Plugin which extracts all strings into references to values in object hashes keyed by language to ease localization efforts (or automate them).
- Plugin which detects subtree duplication in any UNIST compatible tree using this [algorithm](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3996578/) or equivalent (free code duplication detection!)
- Recode -> Remark Bridge which pulls the block comments into paragraphs, and collapses the javascript AST into markdown code blocks. (Think [dox](https://github.com/tj/dox), but more generalized )
- Remark -> Recode Bridge which does the reverse transformation

---
**2.** Absolutely. I'll start putting my own issues and TODOs on this repo for others to chip away at. The larger wants are in the form of questions:
- Is there a lossless mapping between the AST of all programming languages, or a majority subset of those who are descendants of Lisp, and what does it look like in a UNIST style?
- Is there a lossless mapping between Babel's Babylon AST and the standard Parser API ESTree specification, and what does it look like in a UNIST style?
- Can ESTree's formal generator be recruited to generate UNIST specifications? Is there a place for TypeScript in this world?
- How can the Espree parser be swapped out for the core Acorn parser? Is there an elegant way to pass in Acorn plugins to a Unified interface?
- Should Recode be founded upon the Acorn or Babel's Babylon parser? With the Acorn parser, we get easy legacy support for a large ecosystem of ESTree compatible tools, with the Babel parser, we have a larger community of tooling to prepare the tree for Unified style transformers.
- If Babel's Babylon parser, is there an elegant way to pass in Babel plugins to a Unified Interface?

**Comment by JDvorak** [comment]
All that said, I won't be able to dedicate much time to this or my major project [mapcast](https://github.com/JDvorak/mapcast) until the New Year begins.

**Comment by wooorm** [comment]
Awesome! Great to hear.

The new year is very close, go celebrate! ;)

To be completely honest, I’m not very familiar with syntax trees for programming languages. They were, of course, a great inspiration to me when “designing” unist, but I’ve since stayed on markup languages and natural language, and never jumped to “programming”.

I do have a better feeling for Babylon. But Acorn and ESTree are really good as well. Don’t take my word for it, though. one thing I like is Babel’s take on plugins and the ecosystem.

I can see two roads going forward:

1. Create a new syntax tree format, based on unist: recreate plugins specifically made for unified/vfile/unist. This results in fast plugins, specifically made for unified. Very fast, very good. But “duplicates” / “forks”
2. Create two interfaces: Acorn and Babylon interfaces of recode; wrap plugins to work with a syntax tree and a vfile. This results in a Grunt- or Gulp-like ecosystem. Lots of wrappers. However, more things will be supported faster. The downside being: why even use this over Babylon / Acorn directly?

I took 1) for rehype. It takes a lot of time to create plugins ([rehype-minify](https://github.com/wooorm/rehype-minify) is very good, [rehype-format](https://github.com/wooorm/rehype-format) makes very nice HTML too with lots of options). It’ll take a long time for it to become useful over alternatives. But as it’s very high-quality code, pretty speedy, and custom-made for the tool, eventually using one syntax format will become a good combo to opt for.

> Is there a lossless mapping between the AST of all programming languages or a majority subset of those who are descendants of Lisp, and what does it look like in a UNIST style?

There’s [Pandoc](http://pandoc.org) for markup languages. Nothing for programming languages—to my knowledge.

> Is there a lossless mapping between Babel's Babylon AST and the standard Parser API ESTree specification, and what does it look like in a UNIST style?

I think so? Do you have a definition for recode’s AST? Something like mdast/nlcst/hast?

> Can ESTree's formal generator be recruited to generate UNIST specifications? Is there a place for TypeScript in this world?

Probably, I don’t know! I haven’t used typescript, but third-parties have created definitions for my modules. I don’t know, but yeah, I guess so?!

> How can the Espree parser be swapped out for the core Acorn parser? Is there an elegant way to pass the pass in Acorn plugins to a Unified interface?

Think of it like retext-dutch or `retext-english`: the default in `retext` is to use something sensible, but users can use `unified` directly too, and choose their own parser: `recode-acorn` or `recode-babylon`.

> Should Recode be founded upon the Acorn or Babel's Babylon parser? With the Acorn parser, we get easy legacy support for a large ecosystem of ESTree compatible tools, with the Babel parser, we have a larger community of tooling to prepare the tree for Unified style transformers.

The one with the most traction moving forward.
I personally try to write as much ES3 as possible, so I don’t care 😉

**Comment by JDvorak** [comment]
Well, you are in luck: abstract syntax trees for programming languages are _even easier!~_ None of the beautiful ambiguity of natural language is present, so many things become much easier. However, what don't exist, and where I'd like to go, is toward the emulation of work done in computational linguistics. It is likely possible to identify such things as design patterns as if they were [rhetorical maneuvers](http://computationalrhetoricworkshop.uwaterloo.ca/wp-content/uploads/2016/06/Automated-Annotation-and-Visualization-of-Rhetorical-Figures.pdf), and to consider variable naming as stylistic and structured.

As to 'one syntax specification to rule them all, or shims galore,' ultimately, **all roads lead through a single tree specification** Even with a loose gulp ecosystem, a single common tree and vfile form will have to emerge for these plugins to inter-operate. The question is, and it will only really be answered via the work of working it out, the question is: **is there a one common (and elegant) tree specification that stands in the union of Acorn, Babel, and Unified?** 

Already, we can guess that it should be a sibling to MDAST, etc-- but what is the lossless labeling of nodes which can map to both Acorn's ESTree, and Babel's modified-ESTree? In the worst world, there are four trees at play, a strictly Acorn jsAST (as it currently stands, this is what the present case is equivalent to), and a strictly Babel jsAST, and two implicit trees which represents the mapping between Acorn to jsAST(Acorn), and Babylon to jsAST(Babel). This would look something like a key on the module or root node which marks what dialect of jsAST we are about to traverse. Yuck. 

Instead, I have hope that the tree definition implicit in the mapping between jsAST(Acorn) and jsAST(Babel) can be worked out and taken as THE definition of jsAST. Here, you can see how much Pandoc has influenced me. PanDoc for Javascript abstract syntax trees. It is this that I have not begun work on, as I decided to make it easier to iterate and revise the definition with the use of MapCast. 


In the bigger scheme of things, my concerns about rewriting all plugins versus finding a way to absorb the larger ecosystems are long and complicated. The thoughts are pretty well summarized by Richard Gabriel in his classic [essay](https://www.dreamsongs.com/RiseOfWorseIsBetter.html), and [supplemental](https://www.dreamsongs.com/WorseIsBetter.html). Must reading, for these fashionable javascript days.

**Comment by JDvorak** [comment]
Oop! Nope! Documentation will have to be next week.

**Comment by JDvorak** [comment]
Apologies for the delay, @oyeanuj. There are usage documents up now! It is better you waited: I had incorrectly interpreted a few node types, but I detected them with the new fleet of tests for basic core AST node types.

**Comment by JDvorak** [comment]
@wooorm After some consideration, I've decided I'll be replacing the core parser with the [Babylon](https://github.com/babel/babylon) parser. It has greater support, a more active ecosystem, and its custom AST is a superset of the [ESTree](https://github.com/estree/estree)/[Parser API](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API) specification. 

You can look forward to this next change after the next version of [MapCast](https://github.com/JDvorak/mapcast) is stable. I have no desire to write out another monstrous tangle of case statements. 😝

**Comment by wooorm** [comment]
Great points, sorry I took so long to respond.
Very interesting indeed, I think I agree on babylon. Let’s see what comes out, and do hit me up with any further questions! :)
